# MongoDB
spring.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Weather API
weather.api.key=${WEATHER_API_KEY}
weather.api.url=${WEATHER_API_URL}

# ElevenLabs
elevenlabs.api.key=${ELEVENLABS_API_KEY}
elevenlabs.api.url=${ELEVENLABS_API_URL}
elevenlabs.voice.id=${ELEVENLABS_VOICE_ID}


# Gemini
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}
gemini.model=${GEMINI_MODEL}

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379