# MongoDB
spring.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Weather API
weather.api.key=${WEATHER_API_KEY}
weather.api.url=https://api.weatherapi.com/v1/current.json

# ElevenLabs
elevenlabs.api.key=${ELEVENLABS_API_KEY}
elevenlabs.api.url=https://api.elevenlabs.io/v1/text-to-speech
elevenlabs.voice.id=${ELEVENLABS_VOICE_ID}


# Gemini
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/interactions
gemini.model=${GEMINI_MODEL}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}