spring:
  data:
    mongodb:
      auto-index-creation: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: com.princegcs.JournalApplication.model

weather:
  api:
    url: https://api.weatherapi.com/v1/current.json

elevenlabs:
  api:
    url: https://api.elevenlabs.io/v1/text-to-speech

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/interactions

springdoc:
  swagger-ui:
    path: /journal-api

  api-docs:
    path: /journal-api-docs
